### ISSUE TITLE
What about multiple states in one object?

### ISSUE THREAD

**Issue by garrettw** [sebastianbergmann/state#1]
As I read through your example code using a door as the object, I thought to myself: in a real-world door, some of these states are not technically mutually exclusive – and surely a scenario could arise where a PHP object would need to store multiple non-exclusive states.

The locked state in your door example implies that the door is closed, which I'm sure is fine if that's all the functionality you really need (and in this case, it surely is). But humor me for a moment.

I see two states that could be stored: the position of the door (open/closed) and the position of the lock (locked/unlocked). When I take this viewpoint and apply it in a way that resembles the real-world object, I notice that it is possible to open a door, lock it, and then be prevented from closing it. So how would/should this be represented?

- Should the `Door` object store two separate states?
  - If so, then should the Door class decide how to juggle the two states, like testing the lock position to decide whether to call `OpenDoorState::close()`?
  - Or should `OpenDoorState::close()` react differently based on the lock position?
    - If so, should `close()` accept the lock state object as a parameter in order to test its classname?
    - Or should it call some method on the param, or something else??

**Comment by sebastianbergmann** [comment]
The example is indeed simplified. The alternative to this would be to implement door and lock separate from each other (with door aggregating the lock).
